MusicStore/MusicStore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Models;

namespace MusicStore.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        MusicStoreEntity db = new MusicStoreEntity();   
        // GET: Order
        public ActionResult Index()
        {
            var list=db.Orders.Where(p => p.Username == User.Identity.Name).ToList();
            return View(list);
        }

        public ActionResult Details(int id)
        {
            var list = db.OrderDetails.Where(p => p.OrderId == id).ToList();
            return View(list);
        }
    }
}

MusicStore/MusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Models;

namespace MusicStore.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        MusicStoreEntity db = new MusicStoreEntity();
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cartList=db.Carts.Where(a => a.CartId == User.Identity.Name).ToList();

            decimal total = 0;
            foreach (var item in cartList)
            {
                total += item.Count * item.Albums.Price;
            }

            ViewBag.CartTotal = total;
            return View(cartList);
        }

        public ActionResult AddToCart(int id,int count)
        {
            var album = db.Albums.Find(id);
            if (album != null)
            {
                var cartItem= db.Carts.SingleOrDefault(p => p.AlbumId == id&&p.CartId==User.Identity.Name);
                if (cartItem != null)
                {
                    cartItem.Count+=count;
                }
                else
                {
                    cartItem = new Carts()
                    {
                        AlbumId = id,
                        CartId = User.Identity.Name,
                        Count = count,
                        DateCreated = DateTime.Now
                    };
                    db.Carts.Add(cartItem);
                }
                db.SaveChanges();
            }
           
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromCart(int id)
        {
            var cartItem=db.Carts.SingleOrDefault(p => p.RecordId == id&&p.CartId==User.Identity.Name);
            if (cartItem != null) { 
                db.Carts.Remove(cartItem);               
                db.SaveChanges();
            }

            var result = new
            {
                ItemID = id,
                CartTotal = ShoppingCart.CartTotal,
                CartCount=ShoppingCart.CartCount
            };

            return Json(result);
        }

        public ActionResult UpdateItemCount(int id,int count)
        {
            var cartItem = db.Carts.SingleOrDefault(p => p.RecordId == id &&
            p.CartId == User.Identity.Name);

            if (cartItem != null)
            {
                cartItem.Count = count;
                db.SaveChanges();
            }
            var result = new
            {
                ItemID = id,
                CartTotal = ShoppingCart.CartTotal,
                CartCount = ShoppingCart.CartCount
            };

            return Json(result);
        }
        [AllowAnonymous]
        public ActionResult GetCartSummary()
        {
            ViewBag.Count = ShoppingCart.CartCount;
            return PartialView("_CartSummary");
        }
    }
}

MusicStore/MusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MusicStore.Models;
using X.PagedList;


namespace MusicStore.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntity db = new MusicStoreEntity();

        [Authorize(Roles ="admin,user")]//开启用户验证
        //[Authorize(Users ="")]
        // GET: Store
        public ActionResult Index(string search,int page=1)
        {
            var pageSize = 24;
            IPagedList<Albums> list = null;
            if (string.IsNullOrEmpty(search))
            {
                list = db.Albums.OrderByDescending(a => a.AlbumId).ToPagedList(page, pageSize);
            }
            else
            {
                ViewBag.search = search;
                list = db.Albums.Where(a=>a.Title.Contains(search)).OrderByDescending(a => a.AlbumId).ToPagedList(page, pageSize);
            }                       
            
            return View(list);
        }

        public ActionResult Details(int id)
        {
            Albums a=db.Albums.Find(id);
            return View(a);
        }
    }
}

MusicStore/MusicStore/Controllers/StoreManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicStore.Models;

using X.PagedList;

namespace MusicStore.Controllers
{
    [Authorize(Roles ="admin")]
    public class StoreManagerController : Controller
    {
        private MusicStoreEntity db = new MusicStoreEntity();

        // GET: StoreManager
        public ActionResult Index(int page=1)
        {
            var albums = db.Albums.Include(a => a.Artists).Include(a => a.Genres)
                .OrderByDescending(a=>a.AlbumId);
            return View(albums.ToPagedList(page,30));
        }

        // GET: StoreManager/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albums albums = db.Albums.Find(id);
            if (albums == null)
            {
                return HttpNotFound();
            }
            return View(albums);
        }

        // GET: StoreManager/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name");
            return View();
        }

        // POST: StoreManager/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Albums albums,
            HttpPostedFileBase imageFile)//添加参数
        {
            if (ModelState.IsValid)
            {
                if(imageFile != null)
                {
                    string guid=Guid.NewGuid().ToString();
                    string imageName =guid+ Path.GetFileName(imageFile.FileName);//使用Path需using System.IO;
                    string serverPath = Server.MapPath("~/Content/Images/"+imageName);
                    imageFile.SaveAs(serverPath);

                    albums.AlbumArtUrl = "/Content/Images/"+imageName;
                }
                db.Albums.Add(albums);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", albums.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", albums.GenreId);
            return View(albums);
        }

        // GET: StoreManager/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albums albums = db.Albums.Find(id);
            if (albums == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", albums.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", albums.GenreId);
            return View(albums);
        }

        // POST: StoreManager/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlbumId,GenreId,ArtistId,Title,Price,AlbumArtUrl")] Albums albums)
        {
            if (ModelState.IsValid)
            {
                db.Entry(albums).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "ArtistId", "Name", albums.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "GenreId", "Name", albums.GenreId);
            return View(albums);
        }

        // GET: StoreManager/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Albums albums = db.Albums.Find(id);
            if (albums == null)
            {
                return HttpNotFound();
            }
            return View(albums);
        }

        // POST: StoreManager/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Albums albums = db.Albums.Find(id);
            db.Albums.Remove(albums);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MusicStore/MusicStore/Views/Shared/_AlbumDetails.cshtml
@model MusicStore.Models.Albums

<div>
    <h4>Albums</h4>
    <hr />
    <div><img src="@Model.AlbumArtUrl" /></div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artists.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artists.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genres.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genres.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AlbumArtUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumArtUrl)
        </dd>
        @using (Html.BeginForm("AddToCart","ShoppingCart",FormMethod.Get))
        {
        @*@Html.Hidden("id",Model.AlbumId);*@    
        <dt>数量</dt>
        <dd>
            <input type="text" id="txt-count" name="count" value="1" />
        </dd>
        <dt><input name="id" value="@Model.AlbumId" type="hidden" /></dt>
        <dd><input type="submit" class="btn btn-primary" value="加入购物车" /></dd>
        }
     
    </dl>
</div>
<p>
    @*@Html.ActionLink("加入购物车", "AddToCart", "ShoppingCart", new { id = Model.AlbumId }, new { })*@
</p>

MusicStore/MusicStore/Views/Shared/_AlbumList.cshtml
@model IEnumerable<MusicStore.Models.Albums>

<div class="row">
    @foreach (var album in Model)
    {
        <div class="col-md-4">
            <p>
                <a href="@Url.Action("Details","Store",new {id=album.AlbumId })"> <img src="@album.AlbumArtUrl" alt="@album.Title" /></a>
            </p>
            <p>名称：@album.Title</p>
            <p>价格：@album.Price</p>
        </div>
    }
</div>

MusicStore/MusicStore/Views/Shared/_CartSummary.cshtml
<ul class="nav navbar-nav navbar-right">
    <li>
        <a href="@Url.Action("Index","ShoppingCart")">
            <img src="~/Content/Images/cart.png" /><text id="cart-count">购物车(@ViewBag.Count)</text>
        </a>
    </li>
</ul>

MusicStore/MusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("商品浏览", "Index", "Store")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("商品管理","Index","StoreManager")</li>
                    }
                    <li>@Html.ActionLink("我的订单","Index","Order")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                    @{Html.RenderAction("GetCartSummary","ShoppingCart");}
                    
                    @Html.Partial("_LoginPartial")
</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>